version: "3.9"
services:
  server:
    build: .
    ports:
      - "4001:4001"
    command: ./run-server-dev.sh captain/server/server-dev-docker.yml
    working_dir: /captain/
    volumes:
      - ./:/captain/
  webapp:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /captain/web/
    stdin_open: true
    volumes:
      - ./web:/captain/web/
      - /captain/web/node_modules/
