name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out captain source
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: python3.8 -m pip install -r dev.requirements.txt
      - name: Run unit tests
        run: python -m pytest -vv tests/unit/
